on: push

name: Build Release
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master 
      - uses: actions/setup-go@v2 
        with:
          go-version: "1.19.3" 

      - run: go build -o gophergo_linux_amd64
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o gophergo_windows_amd64.exe 
      - run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o gophergo_darwin_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          files: |
            gophergo_linux_amd64
            gophergo_windows_amd64.exe
            gophergo_darwin_amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
